# Site settings
title: Renovamen
SEOTitle: Renovamen (Xiaohan Zou)
email: renovamenzxh@gmail.com
description: Xiaohan Zou's blog
keyword: ""
url: "https://renovamen.ink"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
avatar: "img/header-avatar.jpeg" # the avatar showing on the homepage


# Theme style settings
theme_style: 
  highlight: # "default" (default), "tomorrow-light", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
  alert:  # "flat" (default), "modern"
  # Whether or not to display post's featured image on home page
  post_preview: # "image" (default), "text"


# Markdown enhancements settings
math: 
  enable: true # false (default), true 
               # math rendering for all posts and keynotes
  engine: # "katex" (default), "mathjax"
chart: true # false (default), true
mermaid: true # false (default), true
emoji-plus: true # false (default), true


# CDN source settings
cdn: # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"


# Publish posts or collection documents with a future date.
future: true

collections:
  experience:
    output: true

# SNS settings
sns:
  RSS: true
  github_username: Renovamen
  weibo_username:     
  zhihu_username:     
  twitter_username:   
  facebook_username: renovamen.zou
  linkedin_username:  # firstname-lastname-idxxxx
  email_address: renovamenzxh@gmail.com


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CH.md
  - LICENSE
  - Gruntfile.js
  - /node_modules
  - /docs
anchorjs: true                          # if you want to customize anchor. check out `anchor.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jemoji



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Navigation menu settings
menus:
  - title: Home
    font: fab fa-fort-awesome
    url: /
  - title: About
    font: fas fa-paw
    submenus:
      - title: Me
        font: fas fa-user-astronaut
        url: /about/
      - title: Theme
        font: fas fa-meteor
        url: /theme/
  - title: Archive
    font: fas fa-archive
    url: /archive/
  - title: Portfolio
    font: fas fa-jedi
    url: /portfolio/
  - title: Links
    font: fas fa-link
    url: /links/


# Comment settings
comment: 
  provider: gitalk # false (default), "disqus", "gitalk", "valine"

  # Disqus settings
  disqus_username: renovamen

  # Gitalk settings
  # https://github.com/gitalk/gitalk
  gitalk:
    clientID: 'd6247712dc288a5a60ca'
    clientSecret: 'ed1ec72417828343c79ed910a1b77d140fa715a7'
    repo: gitalk-comments
    owner: This-is-an-Apple
    admin: 
      - Renovamen
      - This-is-an-Apple

  # Valine settings
  # https://valine.js.org/
  valine:
    appID:
    appKey:


# Analytics settings
analytics:
  # Baidu Analytics 
  ba_track_id: # [your track id]

  # Google Analytics
  google:
    ga_track_id: 'UA-146858305-1'            # Format: UA-xxxxxx-xx
    ga_domain: renovamen.ink



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Whether or not to enable Hitokoto (the bubble on homepage)
hitokoto: true # default: false