# Site settings
title: "Renovamen"
SEOTitle: Xiaohan Zou
email: renovamenzxh@gmail.com
description: "Xiaohan Zou's blog"
keyword: ""
url: "https://renovamen.ink"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
header-img: [
  {
    url: img/home-bg/1.jpg,
    mask: "rgba(40, 57, 101, .4)",
  },
  {
    url: img/home-bg/2.jpg,
    mask: "rgba(31, 64, 87, .2)",
  },
  {
    url: img/home-bg/3.jpg,
    mask: "rgba(68, 74, 83, .1)",
  },
  {
    url: img/home-bg/4.jpg,
    mask: "rgba(19, 75, 50, .2)",
  },
]


# Publish posts or collection documents with a future date.
future: true

collections:
  experience:
    output: true

# SNS settings
RSS: false
github_username:    Renovamen
#weibo_username:     
#zhihu_username:     
#twitter_username:   
facebook_username:  renovamen.zou
#linkedin_username:  firstname-lastname-idxxxx
email_address: renovamenzxh@gmail.com


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Comment settings
# Disqus settings
# disqus_username: renovamen

# Gitalk settings
gitalk:
  clientID: 'd6247712dc288a5a60ca'
  clientSecret: 'ed1ec72417828343c79ed910a1b77d140fa715a7'
  repo: gitalk-comments
  owner: This-is-an-Apple

# Valine settings
# valine:
#   appID: 
#   appKey: 



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-146858305-1'            # Format: UA-xxxxxx-xx
ga_domain: renovamen.ink



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "When you are looking at the stars, please put the brightest star shining night sky as my soul."
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Exclude files
exclude:
  - README.md
  - /docs


# Friends (side bar)
friends: []

# Links
links: [
  {
    link-title: "What are these",
    link-list: [
      {
        sitename: "nazo",
        href: "https://nazo.io/",
        img: "img/nazo.jpg",
        linkdes: "???",
      },
    ],
  },
  {
    link-title: "It is time to catch fish",
    link-list: [
      {
        sitename: "IGN",
        href: "http://www.ign.com/?ccpref=US",
        img: "img/ign.jpg",
        linkdes: "Practice English",
      },
      {
        sitename: "GAMECORES",
        href: "https://www.gcores.com",
        img: "img/gamecores.jpeg",
        linkdes: "All-embracing",
      },
      {
        sitename: "VGTIME",
        href: "http://www.vgtime.com",
        img: "img/vgtime.jpeg",
        linkdes: "Game info",
      },
    ],
  }
]