import 'oh-vue-icons/icons/fa/brands/fort-awesome'
import 'oh-vue-icons/icons/fa/paw'
import 'oh-vue-icons/icons/fa/tag'
import 'oh-vue-icons/icons/fa/satellite-dish'
import 'oh-vue-icons/icons/ri/link-m'