# This is a basic workflow to help you get started with Actions

name: build and deploy Jekyll automatically

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build
      - name: build
        run: jekyll build
      
      # Prepare git environmentt
      - name: env
        run: |
          cd site
          git init
          git config user.name "${{secrets.GITHUB_NAME}}"
          git config user.email "${{secrets.GITHUB_EMAIL}}"
          git add .
      
      # Deploy: push to gh-pages branch
      - name: deploy
        run: |
          git commit -m "action build"
          git push --force "https://${GITHUB_TOKEN}@github.com/renovamen.github.io.git" master:gh-pages
